language: python
os:
  - linux
python:
  - "2.7"
before_install:
  - sudo apt-get install cython
  - pip install -r dev-requirements.txt
install: "pip install -r requirements.txt"
script: pytest tests
